### PR TITLE
adding larger base and 20ml glass vials

### PR DESCRIPTION
**Pull request by CamDavidsonPilon**
👋 Very fun designs! 

I have some interesting ideas for how we might modify this for our [Pioreactor](https://pioreactor.com/) project, but here are two contributions so far:

1. a 4x4 base.
2. a modification for 20ml vials (28mm diameter). We use these vials for our system.

I've added stl and ipt files, however this was designed and exported in Fusion 360, so I can't verify if the ipt are correct. 

Screen Shot 2022-08-20 at 4 17 18 PM
Screen Shot 2022-08-20 at 4 17 37 PM

### CODE REVIEW

**Comment by oplz** [comment]
Cool!  Love your Pioreactor! 

Our 50 ml rack is 29mm in diameter.  Will it work with your glass vials? ( https://github.com/oplz/DormantBioLabResources/blob/main/Prints/dovetailed_rack/Inventor_files/50ml_tube_rack.ipt )

Will love to add yours if they are not redundant.  (we also have the 1x2, 2x2 blank blocks but forgot to put them here.  You reminded us :) )  Thanks so much!

Gonna say again, really your Pioreactor, very impressive!!!

**Comment by CamDavidsonPilon** [comment]
We tried the 29mm - just a bit too much wiggle room.

Since you've uploaded the nxm bases (awesome!), that's half this PR. The 28mm probably isn't broad enough for inclusion. 

I'll close this PR, but the 28mm files are still part of the fork, so motivated users can find them there :)

**Comment by oplz** [comment]
Hello!  Since the 29mm doesn't fit the glass vial, we are more than happy to merge your design (with full credit) if you are ok with this. 

It will be helpful for someone and hopefully motivate people to create more varieties.  Let me know! Thanks!!

**Comment by oplz** [comment]
Wonderful!  This is awesome.  Hopefully people will be motivated and make this set more useful with time. Thanks!

**Pull request closed without merging**
